[package]
name = "dhbw-typst-horb"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["etwasmitbaum", "Jannik980", "Roland Schätzle <@roland-KA>", "Danny Seidel <@DannySeidel>"]
license = "MIT"
description = "A Typst Template for DHBW Stuttgart"
repository = "https://github.com/etwasmitbaum/dhbw-typst-horb"
keywords = ["dhbw", "thesis"]
categories = ["paper", "thesis", "report"]
exclude = ["template/main.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"